### PR TITLE
Added information for shape 19 (AsP3)

### PR DESCRIPTION
**Pull request by sichaox**
Sorry, I made two commits on my own fork. I misstyped shape 18 in the first commit.

### CODE REVIEW

**Comment by ndattani** [comment]
Are all dihedral angles for this molecule the same?

**Comment by sichaox** [comment]
> Are all dihedral angles for this molecule the same?

There are two different dihedral angles: one between the As-P-P and As-P-P plane and the other between the P-P-P and As-P-P plane. Do you want me to conclude both as phi_1 and phi_2?

**Comment by sichaox** [comment]
I've just added the other dihedral as well just in case your answer was yes. I just made a new commit.

**Comment by ndattani** [comment]
@sichaox cos(theta)/sin(theta) is just cot(theta) right? Also, two comments ago you included your response to my question, inside a quote. I did indeed want to see the second dihedral angle formula, but more importantly, the table originally had only one dihedral angle and made it look like there's only one possible dihedral angle.

**Comment by ndattani** [comment]
@sichaox  can you please edit your comment with the error in formatting?

**Comment by sichaox** [comment]
> @sichaox can you please edit your comment with the error in formatting?

Done!

**Pull request merged**
