### PR TITLE
Added existing molecules

### PR DESCRIPTION
**Pull request by sichaox**
I've added most of the existing molecules I can find now. However after making the commit I realise I'm having the same problem as before again. The previous bibtex commit just keep re-appearing. I think it's because I didn't pull before pushing?
The models missing are:
Coov: H2BN (I did find [C2HF](https://pubchem.ncbi.nlm.nih.gov/#query=C2HF) which also works, could we perhaps replace H2BN?)
D4h: S42+
C2v: S4
C2h: H2N2
Cs: Cl2S2

### CODE REVIEW

**Comment by ndattani** [comment]
I recommend to always pull before pushing. Also, you need to make a new branch in your fork called "figures" and a new branch in your fork called "bibliography". Then you can make a pull request to have your "figures" merged from sichaox:figures -> HPQC-LABS:main, and you can make a separate pull request to have your "bibliography" merged from sichaox:bibliography -> HPQC-LABS:main. Instead what you're trying to do is to merge sichaox:main -> HPQC-LABS:main. Please do not mix two different features into one pull request unless you're 100% certain that the maintainer(s) of the repository want you to do it that way or once you're much more experienced. My advice in this comment is not just for HPQC LABS repositories: anywhere in the world that you work or collaborate, people will appreciate if you do not create extra confusion by mixing two different added features into one pull request.

**Comment by ndattani** [comment]
Sure, you can use C2HF instead of H2BN. Please acknowledge if you've read and understood my comments here,.

**Comment by sichaox** [comment]
Yes I understand now. I will make a separate branch.

**Comment by ndattani** [comment]
The reason for my first comment in this thread was because you wrote:
> " However after making the commit I realise I'm having the same problem as before again. The previous bibtex commit just keep re-appearing. "

I was explaining why you were experiencing that issue and how to resolve it. 

However you had already reverted the bibtex commit in this pull request (only 44 files were changed, and they were the 44 figures that you were adding). Therefore this pull request could have been merged as it was. I just wanted to make sure that you'd seen my comments before going ahead with the merge.

By now you're aware that I don't like duplicate pull requests even if they are closed. I request that you add the 44 figures to this branch (the main branch) so that this pull request gets updated accordingly and so that I can merge it. Then the next time you update the figures you can do it to the figures branch and we can use #16 for that.

**Pull request merged**
