### PR TITLE
Added imaginary models

### PR DESCRIPTION
**Pull request by sichaox**

### CODE REVIEW

**Comment by ndattani** [comment]
@sichaox  have you not noticed that this branch had conflicts (since the very beginning)? I also told you twice in the HPQC Discord group that I had already added the Randall Shirts paper to references.bib, so by adding it yourself you may have created a conflict. Furthermore, references.bib has nothing to do with this feature request and would be more appropriate to be added in a separate pull request.

**Comment by ndattani** [comment]
Please revert the last commit, which added references.bib to this branch.

**Comment by sichaox** [comment]
Hi @ndattani , I have reverted the bibtex commit.

**Comment by ndattani** [comment]
Thank you! It looks like you force-pushed the main branch of the main fork into this branch in order to remove the conflicts. In general it's discouraged to force-push anything. Were you not able to just "revert" the commit in your own branch, without doing anything associated with the main fork?

**Comment by sichaox** [comment]
On the guides I read online when I use git rebase -i <commit-id> then I must do a force push. If I used git revert it would generate an extra commit to revert the previous commit and this would not require a force push. I chose to keep the commit history tidy so I went with the first option.

**Comment by ndattani** [comment]
@sichaox next time when you are faced with two options, please ask which one is preferred.

**Comment by ndattani** [comment]
@sichaox I can accept this pull request but I don't know whether or not you've read my last message. Can you please acknowledge that you've seen it, in some way?

**Comment by sichaox** [comment]
Yes, I confirm that I have seen it.

**Pull request merged**
