### PR TITLE
Added models for point groups.

### PR DESCRIPTION
**Pull request by sichaox**

### CODE REVIEW

**Comment by ndattani** [comment]
I asked this in the HPQC Discord server but it's probably better to ask it here: Why is there an "acesin" file for C2h but not for other point groups? Please see the screenshot below:

image

**Comment by ndattani** [comment]
@sichaox please also remove the axis from each image.

**Comment by sichaox** [comment]
No problem, I'll crop the images. I have removed the C_2h.acesin file. I was experimenting with other file types for saving and forgot to delete it.

**Comment by ndattani** [comment]
Also, it would make more sense for the 2-atom "base" to be the same color as the 3-atom, 4-atom, 5-atoms etc. "bases":

image

**Comment by ndattani** [comment]
@sichaox you have not changed the colors for the Dnd series yet. Also the diagrams for Dnd don't make it clear that the n-gons are on different planes. Same for the Dn series.

**Comment by sichaox** [comment]
I don't get what you mean by changing colours. It's meant to be A_2n.

**Comment by sichaox** [comment]
I think the overlapping of the bonds does make it clear though? If I make it a different colour it'll be hard to recognize that they represent the same type of atom.

**Comment by ndattani** [comment]
Is it possible to make it more clear what is going on for D2 and D2d? Right now these just look like two pyramids that are being viewed from different angles: 
image

**Comment by sichaox** [comment]
I could make the rhombic disphenoid more scalene to differentiate.

**Comment by ndattani** [comment]
> "I think the overlapping of the bonds does make it clear though? If I make it a different colour it'll be hard to recognize that they represent the same type of atom." 

I don't think that the overlapping bonds makes it clear to everyone, that the two n-gons are on different planes. Maybe the angle can be adjusted so that we can see that these two n-gons are on different planes?

**Comment by sichaox** [comment]
Then it may be hard to see that they are n-gons that are exterior angle/2 rotated from each other. Either way we need to make compromises now.

**Comment by ndattani** [comment]
For D2, in order to follow more closely with the pattern of what we see for D3,D4,etc., perhaps we can just have a diatomic molecule on each of the two planes, and having the 10 degrees (or whatever it is) rotation applied to one of them, just like we did for D3 and the rest of the point groups in the Dn series? For D2d can we not have a "+" sign with the two lines being on different planes (just like you have for the base of the S4 model)?

**Comment by ndattani** [comment]
@sichaox also for D2h it would make more sense to draw the diagram with the same orientation as C2h here: 

image

The document by Atikins-Child-Phillips uses a rectangular base for everything except for C2 and C2v, so we can do the same:

image

**Pull request merged**
