### PR TITLE
Added mathematica file

### PR DESCRIPTION
**Pull request by Samrfgh**
Added the mathematica file used to simplify equations for molecules S2F2, C3H, and CsNO2

### CODE REVIEW

**Comment by ndattani** [comment]
Thank you @Samrfgh! I wanted also to ask you to push a CDF (Computable Document Format) file in addition to the .nb file because not everyone in the world has access to the commercial Mathematica license but at least CDF files can be viewed by almost anyone. However I noticed that CDF is now described since 2021 as a "legacy format" which seems to have been replaced by "Wolfram Notebooks". Can you look into this and generate the file that would be most appropriate in terms of conveying the information of the .nb file in a way that still looks the same but can be viewed by everyone? I'm not sure if CDF or Wolfram Notebooks are the best for this!

CDFs were always the file format of choice for me since they first appeared in 2011, but something seems to have changed recently in 2021.

**Comment by Samrfgh** [comment]
It seems that the .nb file is already a "wolfram notebook", at least thats the description Mathematica gave when I saved it as a .nb file in the first place. I've also added the cdf file, too.

**Comment by ndattani** [comment]
The CDF player does display the .cdf file reasonably well:

image

I'm only seeing three outputs though, and they are located under a section that says "no simplifications found". Why is that?

Also, @Samrfgh, these FullSimplify commands don't tell Mathematica that r1,r2,etc are all >0.  Many formulas can be greatly simplified once you tell the software that a variable is known to be a real number, or a positive number (for example). Did you have any luck when adding the information that these bond lengths and angles are greater than 0?

Also, it seems that the .cdf file and .nb file both look the same in the CDF player, which is maybe what was expected. Thanks for adding them both anyway! Until a few days ago, I didn't know that the CDF format is being deprecated.

**Comment by ndattani** [comment]
@Samrfgh Perhaps if you "run" all of the FullSimplify functions before saving the .nb or .cdf files, then more outputs will be visible in the files? Public users without a Mathematica license, won't be able to run the commands themselves, they'll just see the results from when you run the commands.

Also, have you figured out yet how to impose "assumptions" such as "r1 > 0" when running FullSimplify?

**Pull request merged**
