### PR TITLE
Added missing parameter formula for molecules 17 & 18

### PR DESCRIPTION
**Pull request by Samrfgh**
Added missing parameter formula for molecules 17 & 18, as well as filled in the corresponding tables with definitions for all the variables

### CODE REVIEW

**Comment by ndattani** [comment]
@Samrfgh 

1) Was it only 17 and 18 that you did?
2) Can you please compile the LyX file to generate a PDF, and push the new PDF to your fork as well? Please remember not to close this pull request or make another branch or fork, and not to open a new pull request.

**Comment by Samrfgh** [comment]
Yes, I only added the formula and changed the table for molecule 17 & 18. I have regenerated the pdf document and it should now be included in the pull request.

**Comment by ndattani** [comment]
I said this in the HPQC Discord as well, but I'll say it here too for completeness:

> "I recommend to make the appropriate substitutions in your formulas for shapes 17 and 18, so that all formulas depend only on the given in formation. Mathematica can do this for you if WolframAlpha cannot. You can use the "FullSimplify" function to "fully" simplify all trig expressions, such as cos(2*arccos(x)), which is one of the expressions that you will have after the substitutions."

**Comment by Samrfgh** [comment]
updated simplified formulas that only included provided parameters

**Comment by ndattani** [comment]
Thanks!

**Comment by Samrfgh** [comment]
I have added the 3 new molecules to the table (shapes 21, 22, and 23), and added the formula, z-matrix etc. to the end of the file

**Comment by ndattani** [comment]
Excellent work @Samrfgh.

I have approved and merged this pull request, but I do want to ask something: Some of these formulas are quite large and complicated. Have you run FullSimplify on all of them?

**Comment by Samrfgh** [comment]
Yes, I have. I think an issue here is that we are working with angles in degrees, so some trig identities which may normally be applicable can't be used here.

**Comment by ndattani** [comment]
@Samrfgh Mathematica would need to know what unit you're using for angles (maybe you've already told Mathematica that you were using degrees). If you switch all instances of "180" to "pi" and try FullSimplify again, does it help? If you can provide the Mathematica code that you used, I can take a look.

**Comment by Samrfgh** [comment]
I have just retried a few cases and unfortunately it doesn't seem to simplify further. The simpler formulas are all very basic trig triangles, or have symmetry. The others formulas are mainly just applications of cosine rules with an odd combinations of angles, so the formula comes out pretty long, especially in cases which there is no symmetry.

**Comment by ndattani** [comment]
@Samrfgh I tried the following formula:

image

in WolframAlpha and did get a significant simplification of the formula (here's a [link](https://www.wolframalpha.com/input?i=arcsin%28r_1%2F%282*%28sqrt%28r_2%5E2+%2B+r_3%5E2+-+2*r_2*r_3*cos%28Pi%2F2+%2B+arccos%28r_1%2F%282*r_2%29%29%29%29%29%29%29)):

image

The new version has 1 more square root symbol, but two fewer trig functions (I'd much rather have a square root symbol than a "cos" and "cos^(-1)" since the square root is a much more "elementary" function and doesn't have the annoyances of an inverse function like cos^(-1). The final formula is also far more compact in terms of the horizontal space occupied on the page (and while it looks like it takes up more vertical space because of the square root, that vertical space will be shrunk once we switch to LaTeX).

Since I was able to get this much simplification done even before telling the program that (r1,r2,r3)>0, and since Mathematica is much more powerful than WolframAlpha, I do think that some of the formulas in the current version of the PDF document can be simplified.

If you're able to check the formulas again with Mathematica, would you be able to save the .nb file  so that others such as @deyanmihaylov with more Mathematica experience can make an attempt to further improve whatever becomes the best that you're able to obtain?

**Comment by Samrfgh** [comment]
Good Find! I have just looked at all the formula again and it seems a few formulas for C3H can be simplified, but not so much for the others. I have the .nb file I used saved now, where should I post it on discord?

**Comment by ndattani** [comment]
@Samrfgh you can make a pull request to add it to this ZMC repository :)

**Pull request merged**
