### PR TITLE
Updated figures

### PR DESCRIPTION
**Pull request by sichaox**

### CODE REVIEW

**Comment by ndattani** [comment]
What is meant by "removed backgrounds"?

**Comment by sichaox** [comment]
Initially I forgot to crop the images in the first commit so I cropped them in the next commit.

**Comment by ndattani** [comment]
@sichaox do you remember why you were asked to revert that commit via the recent force push that you can see here?

**Comment by sichaox** [comment]
I had to force push to revert the commit as I added pdf for n=oo models files with the same names.

**Comment by ndattani** [comment]
> I had to force push to revert the commit as I added pdf for n=oo models files with the same names.

That is almost the complete story: You added the n=oo models ***with labels*** and named them in the same way that the n=oo models ***without labels*** were originally named. Then what happened next?

**Comment by sichaox** [comment]
I remade the pdfs in another software (Ipe) and pushed both the labelled and unlabelled versions with the correct Dooh and Coov labellings this time around. Previously, I also accidently commited the PossibleGroupsForMolecules.lyx~ files which was removed as part of the git reset and force push.

**Comment by ndattani** [comment]
@sichaox 

> "I remade the pdfs in another software (Ipe) and pushed both the labelled and unlabelled versions with the correct Dooh and Coov labellings this time around."

The labelings are one thing, but what about the file names?

**Pull request merged**
